/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as GuidesHoustonWebsiteCostRouteImport } from './routes/guides.houston-website-cost'
import { Route as GuidesSquarespaceVsCustomWebsiteRouteImport } from './routes/guides.squarespace-vs-custom-website'
import { Route as GuidesWebsiteAuditChecklistRouteImport } from './routes/guides.website-audit-checklist'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as ProposalTokenRouteImport } from './routes/proposal.$token'
import { Route as SiteReportTokenRouteImport } from './routes/site-report.$token'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProposalsProposalIdRouteImport } from './routes/_authenticated/proposals.$proposalId'
import { Route as ApiPublicBriefIntakeRouteImport } from './routes/api/public/brief-intake'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicLeadconnectorRouteImport } from './routes/api/public/leadconnector'
import { Route as ApiPublicVapiRouteImport } from './routes/api/public/vapi'
import { Route as ApiPublicAutomationDeliveryRouteImport } from './routes/api/public/automation/delivery'
import { Route as ApiPublicAutomationFollowupsRouteImport } from './routes/api/public/automation/followups'
import { Route as ApiPublicAutomationGscIndexWatchRouteImport } from './routes/api/public/automation/gsc-index-watch'
import { Route as ApiPublicAutomationProspectSyncRouteImport } from './routes/api/public/automation/prospect-sync'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHoustonWebsiteCostRoute =
  GuidesHoustonWebsiteCostRouteImport.update({
    id: '/guides/houston-website-cost',
    path: '/guides/houston-website-cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesSquarespaceVsCustomWebsiteRoute =
  GuidesSquarespaceVsCustomWebsiteRouteImport.update({
    id: '/guides/squarespace-vs-custom-website',
    path: '/guides/squarespace-vs-custom-website',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesWebsiteAuditChecklistRoute =
  GuidesWebsiteAuditChecklistRouteImport.update({
    id: '/guides/website-audit-checklist',
    path: '/guides/website-audit-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalTokenRoute = ProposalTokenRouteImport.update({
  id: '/proposal/$token',
  path: '/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteReportTokenRoute = SiteReportTokenRouteImport.update({
  id: '/site-report/$token',
  path: '/site-report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsProposalIdRoute =
  AuthenticatedProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBriefIntakeRoute = ApiPublicBriefIntakeRouteImport.update({
  id: '/api/public/brief-intake',
  path: '/api/public/brief-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadconnectorRoute = ApiPublicLeadconnectorRouteImport.update({
  id: '/api/public/leadconnector',
  path: '/api/public/leadconnector',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVapiRoute = ApiPublicVapiRouteImport.update({
  id: '/api/public/vapi',
  path: '/api/public/vapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutomationDeliveryRoute =
  ApiPublicAutomationDeliveryRouteImport.update({
    id: '/api/public/automation/delivery',
    path: '/api/public/automation/delivery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationFollowupsRoute =
  ApiPublicAutomationFollowupsRouteImport.update({
    id: '/api/public/automation/followups',
    path: '/api/public/automation/followups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationGscIndexWatchRoute =
  ApiPublicAutomationGscIndexWatchRouteImport.update({
    id: '/api/public/automation/gsc-index-watch',
    path: '/api/public/automation/gsc-index-watch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationProspectSyncRoute =
  ApiPublicAutomationProspectSyncRouteImport.update({
    id: '/api/public/automation/prospect-sync',
    path: '/api/public/automation/prospect-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/brief': typeof BriefRoute
  '/case-study': typeof CaseStudyRoute
  '/clients': typeof ClientsRoute
  '/connect': typeof ConnectRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/guides/houston-website-cost': typeof GuidesHoustonWebsiteCostRoute
  '/guides/squarespace-vs-custom-website': typeof GuidesSquarespaceVsCustomWebsiteRoute
  '/guides/website-audit-checklist': typeof GuidesWebsiteAuditChecklistRoute
  '/portal/login': typeof PortalLoginRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/site-report/$token': typeof SiteReportTokenRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/api/public/brief-intake': typeof ApiPublicBriefIntakeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/leadconnector': typeof ApiPublicLeadconnectorRoute
  '/api/public/vapi': typeof ApiPublicVapiRoute
  '/api/public/automation/delivery': typeof ApiPublicAutomationDeliveryRoute
  '/api/public/automation/followups': typeof ApiPublicAutomationFollowupsRoute
  '/api/public/automation/gsc-index-watch': typeof ApiPublicAutomationGscIndexWatchRoute
  '/api/public/automation/prospect-sync': typeof ApiPublicAutomationProspectSyncRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/brief': typeof BriefRoute
  '/case-study': typeof CaseStudyRoute
  '/clients': typeof ClientsRoute
  '/connect': typeof ConnectRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/guides/houston-website-cost': typeof GuidesHoustonWebsiteCostRoute
  '/guides/squarespace-vs-custom-website': typeof GuidesSquarespaceVsCustomWebsiteRoute
  '/guides/website-audit-checklist': typeof GuidesWebsiteAuditChecklistRoute
  '/portal/login': typeof PortalLoginRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/site-report/$token': typeof SiteReportTokenRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work': typeof WorkIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/api/public/brief-intake': typeof ApiPublicBriefIntakeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/leadconnector': typeof ApiPublicLeadconnectorRoute
  '/api/public/vapi': typeof ApiPublicVapiRoute
  '/api/public/automation/delivery': typeof ApiPublicAutomationDeliveryRoute
  '/api/public/automation/followups': typeof ApiPublicAutomationFollowupsRoute
  '/api/public/automation/gsc-index-watch': typeof ApiPublicAutomationGscIndexWatchRoute
  '/api/public/automation/prospect-sync': typeof ApiPublicAutomationProspectSyncRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/brief': typeof BriefRoute
  '/case-study': typeof CaseStudyRoute
  '/clients': typeof ClientsRoute
  '/connect': typeof ConnectRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/guides/houston-website-cost': typeof GuidesHoustonWebsiteCostRoute
  '/guides/squarespace-vs-custom-website': typeof GuidesSquarespaceVsCustomWebsiteRoute
  '/guides/website-audit-checklist': typeof GuidesWebsiteAuditChecklistRoute
  '/portal/login': typeof PortalLoginRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/site-report/$token': typeof SiteReportTokenRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/api/public/brief-intake': typeof ApiPublicBriefIntakeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/leadconnector': typeof ApiPublicLeadconnectorRoute
  '/api/public/vapi': typeof ApiPublicVapiRoute
  '/api/public/automation/delivery': typeof ApiPublicAutomationDeliveryRoute
  '/api/public/automation/followups': typeof ApiPublicAutomationFollowupsRoute
  '/api/public/automation/gsc-index-watch': typeof ApiPublicAutomationGscIndexWatchRoute
  '/api/public/automation/prospect-sync': typeof ApiPublicAutomationProspectSyncRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/auth'
    | '/book'
    | '/brief'
    | '/case-study'
    | '/clients'
    | '/connect'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/admin'
    | '/portal'
    | '/checkout/return'
    | '/guides/houston-website-cost'
    | '/guides/squarespace-vs-custom-website'
    | '/guides/website-audit-checklist'
    | '/portal/login'
    | '/proposal/$token'
    | '/site-report/$token'
    | '/work/$slug'
    | '/work/'
    | '/.mcp/invoke-tool/$tool'
    | '/projects/$projectId'
    | '/proposals/$proposalId'
    | '/api/public/brief-intake'
    | '/api/public/contact'
    | '/api/public/leadconnector'
    | '/api/public/vapi'
    | '/api/public/automation/delivery'
    | '/api/public/automation/followups'
    | '/api/public/automation/gsc-index-watch'
    | '/api/public/automation/prospect-sync'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/auth'
    | '/book'
    | '/brief'
    | '/case-study'
    | '/clients'
    | '/connect'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/admin'
    | '/portal'
    | '/checkout/return'
    | '/guides/houston-website-cost'
    | '/guides/squarespace-vs-custom-website'
    | '/guides/website-audit-checklist'
    | '/portal/login'
    | '/proposal/$token'
    | '/site-report/$token'
    | '/work/$slug'
    | '/work'
    | '/.mcp/invoke-tool/$tool'
    | '/projects/$projectId'
    | '/proposals/$proposalId'
    | '/api/public/brief-intake'
    | '/api/public/contact'
    | '/api/public/leadconnector'
    | '/api/public/vapi'
    | '/api/public/automation/delivery'
    | '/api/public/automation/followups'
    | '/api/public/automation/gsc-index-watch'
    | '/api/public/automation/prospect-sync'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/audit'
    | '/auth'
    | '/book'
    | '/brief'
    | '/case-study'
    | '/clients'
    | '/connect'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/checkout/return'
    | '/guides/houston-website-cost'
    | '/guides/squarespace-vs-custom-website'
    | '/guides/website-audit-checklist'
    | '/portal/login'
    | '/proposal/$token'
    | '/site-report/$token'
    | '/work/$slug'
    | '/work/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/proposals/$proposalId'
    | '/api/public/brief-intake'
    | '/api/public/contact'
    | '/api/public/leadconnector'
    | '/api/public/vapi'
    | '/api/public/automation/delivery'
    | '/api/public/automation/followups'
    | '/api/public/automation/gsc-index-watch'
    | '/api/public/automation/prospect-sync'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  BriefRoute: typeof BriefRoute
  CaseStudyRoute: typeof CaseStudyRoute
  ClientsRoute: typeof ClientsRoute
  ConnectRoute: typeof ConnectRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  GuidesHoustonWebsiteCostRoute: typeof GuidesHoustonWebsiteCostRoute
  GuidesSquarespaceVsCustomWebsiteRoute: typeof GuidesSquarespaceVsCustomWebsiteRoute
  GuidesWebsiteAuditChecklistRoute: typeof GuidesWebsiteAuditChecklistRoute
  PortalLoginRoute: typeof PortalLoginRoute
  ProposalTokenRoute: typeof ProposalTokenRoute
  SiteReportTokenRoute: typeof SiteReportTokenRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBriefIntakeRoute: typeof ApiPublicBriefIntakeRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicLeadconnectorRoute: typeof ApiPublicLeadconnectorRoute
  ApiPublicVapiRoute: typeof ApiPublicVapiRoute
  ApiPublicAutomationDeliveryRoute: typeof ApiPublicAutomationDeliveryRoute
  ApiPublicAutomationFollowupsRoute: typeof ApiPublicAutomationFollowupsRoute
  ApiPublicAutomationGscIndexWatchRoute: typeof ApiPublicAutomationGscIndexWatchRoute
  ApiPublicAutomationProspectSyncRoute: typeof ApiPublicAutomationProspectSyncRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/houston-website-cost': {
      id: '/guides/houston-website-cost'
      path: '/guides/houston-website-cost'
      fullPath: '/guides/houston-website-cost'
      preLoaderRoute: typeof GuidesHoustonWebsiteCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/squarespace-vs-custom-website': {
      id: '/guides/squarespace-vs-custom-website'
      path: '/guides/squarespace-vs-custom-website'
      fullPath: '/guides/squarespace-vs-custom-website'
      preLoaderRoute: typeof GuidesSquarespaceVsCustomWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/website-audit-checklist': {
      id: '/guides/website-audit-checklist'
      path: '/guides/website-audit-checklist'
      fullPath: '/guides/website-audit-checklist'
      preLoaderRoute: typeof GuidesWebsiteAuditChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$token': {
      id: '/proposal/$token'
      path: '/proposal/$token'
      fullPath: '/proposal/$token'
      preLoaderRoute: typeof ProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-report/$token': {
      id: '/site-report/$token'
      path: '/site-report/$token'
      fullPath: '/site-report/$token'
      preLoaderRoute: typeof SiteReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$proposalId': {
      id: '/_authenticated/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof AuthenticatedProposalsProposalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/brief-intake': {
      id: '/api/public/brief-intake'
      path: '/api/public/brief-intake'
      fullPath: '/api/public/brief-intake'
      preLoaderRoute: typeof ApiPublicBriefIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leadconnector': {
      id: '/api/public/leadconnector'
      path: '/api/public/leadconnector'
      fullPath: '/api/public/leadconnector'
      preLoaderRoute: typeof ApiPublicLeadconnectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vapi': {
      id: '/api/public/vapi'
      path: '/api/public/vapi'
      fullPath: '/api/public/vapi'
      preLoaderRoute: typeof ApiPublicVapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/delivery': {
      id: '/api/public/automation/delivery'
      path: '/api/public/automation/delivery'
      fullPath: '/api/public/automation/delivery'
      preLoaderRoute: typeof ApiPublicAutomationDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/followups': {
      id: '/api/public/automation/followups'
      path: '/api/public/automation/followups'
      fullPath: '/api/public/automation/followups'
      preLoaderRoute: typeof ApiPublicAutomationFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/gsc-index-watch': {
      id: '/api/public/automation/gsc-index-watch'
      path: '/api/public/automation/gsc-index-watch'
      fullPath: '/api/public/automation/gsc-index-watch'
      preLoaderRoute: typeof ApiPublicAutomationGscIndexWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/prospect-sync': {
      id: '/api/public/automation/prospect-sync'
      path: '/api/public/automation/prospect-sync'
      fullPath: '/api/public/automation/prospect-sync'
      preLoaderRoute: typeof ApiPublicAutomationProspectSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProposalsProposalIdRoute: typeof AuthenticatedProposalsProposalIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProposalsProposalIdRoute: AuthenticatedProposalsProposalIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  BriefRoute: BriefRoute,
  CaseStudyRoute: CaseStudyRoute,
  ClientsRoute: ClientsRoute,
  ConnectRoute: ConnectRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  GuidesHoustonWebsiteCostRoute: GuidesHoustonWebsiteCostRoute,
  GuidesSquarespaceVsCustomWebsiteRoute: GuidesSquarespaceVsCustomWebsiteRoute,
  GuidesWebsiteAuditChecklistRoute: GuidesWebsiteAuditChecklistRoute,
  PortalLoginRoute: PortalLoginRoute,
  ProposalTokenRoute: ProposalTokenRoute,
  SiteReportTokenRoute: SiteReportTokenRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBriefIntakeRoute: ApiPublicBriefIntakeRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicLeadconnectorRoute: ApiPublicLeadconnectorRoute,
  ApiPublicVapiRoute: ApiPublicVapiRoute,
  ApiPublicAutomationDeliveryRoute: ApiPublicAutomationDeliveryRoute,
  ApiPublicAutomationFollowupsRoute: ApiPublicAutomationFollowupsRoute,
  ApiPublicAutomationGscIndexWatchRoute: ApiPublicAutomationGscIndexWatchRoute,
  ApiPublicAutomationProspectSyncRoute: ApiPublicAutomationProspectSyncRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
